### ISSUE TITLE
又不能正常运行example

### ISSUE THREAD

**Issue by SOVLOOKUP** [midwayjs/hooks#101]
## 复现步骤

1. 重新clone项目运行example

2. npm run dev 前端请求后端接口失败

打开开发者工具看到前端在3000端口，后端在7001端口

3. npm run build 同样失败

**Comment by Lxxyx** [comment]
是哪个 example，我看看 @SOVLOOKUP

**Comment by SOVLOOKUP** [comment]
所有example都是这样，貌似依赖项出了问题，我用上周的node_modules替换就可以正常运行

**Comment by Lxxyx** [comment]
收到，已复现，排查中

**Comment by Lxxyx** [comment]
已修复，拉取最新代码即可
