### ISSUE TITLE
RFC：单元测试

### ISSUE THREAD

**Issue by Lxxyx** [midwayjs/hooks#11]
本 RFC 旨在提出在 Hooks 项目下的单元测试语法与实现方式。

### 默认调用

> lambda/demo.ts
```ts
export async function get() {
  return 'get'
}

export async function post (value: string) {
  return value
}
```

```ts
import { get, post } from '../demo'
import { invoke } from '@midwayjs/hooks-testing-library'

test('lambda get', () => {
  const { data } = await invoke(() => get())
  expect(data).toEqual('get')
})

test('lambda post', () => {
  const { data } = await invoke(() => post('from test'))
  expect(data).toEuqal('from test')
})
```

### 设置 Context

> lambda/demo.ts
```ts
export async function query() {
  const ctx = useContext()
  return ctx.query
}

export async function header () {
  return ctx.header
}
```

```ts
import { query, header } from '../demo'
import { invoke } from '@midwayjs/hooks-testing-library'

test('lambda with query', () => {
  const { data } = await invoke(() => query(), {
    query: {
      from: 'test'
    }
  })    
  expect(data).toEqual({
    from: 'test'
  })
})

test('lambda with header', () => {
  const { data } = await invoke(() => header(), {
    header: {
      from: 'test'
    }
  })    
  expect(data).toEqual({
    from: 'test'
  })
})
```

### 测试返回信息

> lambda/demo.ts
```ts
export async function setStatus() {
  const ctx = useContext()
  ctx.status = 404
  return null
}

export async function setHeader () {
  const ctx = useContext()
  ctx.set('Access-Control-Allow-Origin', '*')
  return null
}
```

```ts
test('lambda with response status', () => {
  const { data, status } = await invoke(() => setStatus())    
  expect(status).toEqual(404)
})

test('lambda with response header', () => {
  const { data, header } = await invoke(() => setHeader())    
  expect(header['Access-Control-Allow-Origin']).toEqual('*')
})
```

### invoke(lambda, FaaSContext)

```ts
declare function invoke(lambda: Function, context: FaaSContext) :Response

// inspire by axios: https://github.com/axios/axios#response-schema
type Response = {
  // `data` is the response that was provided by the server
  data: {},

  // `status` is the HTTP status code from the server response
  status: 200,

  // `statusText` is the HTTP status message from the server response
  statusText: 'OK',

  // `headers` the HTTP headers that the server responded with
  // All header names are lower cased and can be accessed using the bracket notation.
  // Example: `response.headers['content-type']`
  headers: {},

  // `config` is the config that was provided to test client
  config: {},
}
```

## 技术选型
- Hooks：Jest + ts-jest + Midway Bin + 自研 Testing Library
- 前端：由各前端推荐 Framework 决定，推荐统一使用 Jest + testing-library

## 约定与限制
由于前后端测试环境不同，为避免冲突与不必要的问题，约定如下：

- 后端单测统一存放于 /src/apis 目录下，与源码一同存放（React 单测开发模式）
- 支持测试 lambda，不支持单独测试 hooks，hooks 的测试依赖于 lambda（因为需要自动生成路由与上下文信息）
- 单测由 Midway Bin 启动（封装 Jest 配置与 Env，确保只运行 Hooks 的单测），不支持直接使用 Jest

## 实现方案
使用 ts-jest 提供的 [AST transformers option](https://kulshekhar.github.io/ts-jest/user/config/astTransformers)

将所有导入的 lambda 编译为返回调用信息，并通过 serverless-invoke 做调用。

### 工作流

![Untitled Diagram](https://user-images.githubusercontent.com/13161470/97080314-f897c480-162c-11eb-9bf7-a5634d697f69.png)

## 可能会出现的问题
- SourceMap 映射问题
- 前后端一同运行单测的问题

**Comment by noahziheng** [comment]
1. 单个hook也应该考虑被单测覆盖，可以通过传入mock的FaaSContext的形式实现
2. 前端单测问题未解决，现在应该没build不能直接跑
3. 上下文/返回值中头字段原文写错，应为ctx.headers
4. testing-library invoke第二个参数options应该能覆盖全部FaaSContext，比如mock掉ctx.env，甚至覆盖中间件的client完成mock（日常环境下部分服务gg，且非服务市场的情况）
5. 已有TS类型的情况能否加些糖，支持直接进行全部/部分类型校验，减少断言代码量

**Comment by noahziheng** [comment]
补充：依赖Egg插件的场景中，涉及登陆态的如BUC、ACL、TBSession，当前方案会挂，且没提供有效Mock途径

**Comment by duncup** [comment]
1. 建议考虑与非hook函数并存时的兼容性问题。
2. 建议考虑存在service时对service内函数进行测试的方案。
以上两个需求都在实际项目中遇到过。

**Comment by Lxxyx** [comment]
根据反馈，单测需要考虑的场景：

#### 后端

1. 函数测试
2. Hook 测试（包含 Service 测试）
3. 后端普通函数测试

#### 前端
1. 前端通过 import 使用了函数
2. 前端其它函数测试
3. 前后端 Jest 兼容问题

**Comment by Lxxyx** [comment]
语法：https://gist.github.com/Lxxyx/d793eb3d89129209b64823e83d9824ad
