### ISSUE TITLE
midwayjs V3 创建一体化项目并初始化后，项目运行报错

### ISSUE THREAD

**Issue by dwyanewang** [midwayjs/hooks#193]
// 创建 api 模版
npx degit https://github.com/midwayjs/hooks/examples/api ./hooks-app

// 初始化
npm i 
// 本地运行
npm run dev

// 报错
 hooks-api-starter@1.0.0 dev E:\Dwyanewang\Projects\demo\midway3\hooks-app
 mw dev --fast

- Midway Starting [ Midway ] (node:3364) UnhandledPromiseRejectionWarning: Error: Please add @midwayjs/mock to your devDependencies
    at E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\cli-plugin-dev\src\child.ts:31:11
    at Object.<anonymous> (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\cli-plugin-dev\src\child.ts:81:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)

[ Midway ] (node:3364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

// 安装 @midwayjs/mock 依赖
E:\Dwyanewang\Projects\demo\midway3\hooks-app>npm i -D @midwayjs/mock
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated superagent@3.8.3: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>. Thanks to @shadowgate15, @spence-s, and @niftylettuce. Superagent is sponsored by Forward Email at <https://forwardemail.net>.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

 core-js@2.6.12 postinstall E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\core-js
 node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
 https://opencollective.com/core-js 
 https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @midwayjs/mock@2.14.6
added 161 packages from 247 contributors in 21.362s

50 packages are looking for funding
  run `npm fund` for details

// 再次运行
npm run dev
// 报错
E:\Dwyanewang\Projects\demo\midway3\hooks-app>npm run dev

 hooks-api-starter@1.0.0 dev E:\Dwyanewang\Projects\demo\midway3\hooks-app
 mw dev --fast

\ Midway Starting 
[ Midway ] start error: (0 , core_1.clearContainerCache) is not a function
TypeError: (0 , core_1.clearContainerCache) is not a function
    at create (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\mock\dist\utils.js:74:36)
    at createApp (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\mock\dist\utils.js:168:29)
    at E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\cli-plugin-dev\src\child.ts:47:19
    at Object.<anonymous> (E:\Dwyanewang\Projects\demo\midway3\hooks-app\node_modules\@midwayjs\cli-plugin-dev\src\child.ts:81:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by Lxxyx** [comment]
感谢反馈，可以参考 https://github.com/midwayjs/hooks/commit/edf2e4a75ce3f4b915005b4eaf7f3ae794ea07ee 的改动，修改一下包版本和目录地址
