### ISSUE TITLE
vue-faas 前端如何正确部署?

### ISSUE THREAD

**Issue by raiscui** [midwayjs/hooks#196]
我是新手 我用 v3的hooks :  ‘npx degit https://github.com/midwayjs/hooks/examples/vue-faas ./hooks-app‘ 起了一个项目,  部署到 aliyunFC, 但是我发现 vue 前端没有发布出去, 我想问下在这种情况下,  前端是怎么部署的?

首先 我调整了 
`midway.config.ts` 因为编译不通过: 
```
const vue = require('@vitejs/plugin-vue');
const { defineConfig } = require('@midwayjs/hooks-kit');

module.exports = defineConfig({
    vite: {
        plugins: [vue()]
    }
});
```

我发布使用 npm run build && mw deploy
到 阿里云 FC, 我发现 部署过程并没有 将 生成的 dist/_client 打包到 serverless ,
后来又试用了 midway v1 的 `mindway-hooks-vue3` 模版, 是可以成功的, 我看了下 主要是 `@midwayjs/faas-middleware-static-file` 这个起的作用, 而这个用在 v3上 我也没搞明白怎么用.

后来看到
@midwayjs/static-file
-------------
根据介绍,我使用 @midwayjs/static-file 
先简单手动吧 dist/_client 拷贝到 `build`目录
部署到阿里云FC , 访问结果 404,
没有起作用,

后面我参考 midway v1 的 `mindway-hooks-vue3` , 想是不是要一个 指向‘/’ 首页的api啊, 
于是建了一个 

```
 export const index = Api(Get('/'), async () => {
 });
```
但是 怎么引入static-file 组件 要怎么写没搞明白 
目前就卡在这里

**Comment by Lxxyx** [comment]
#235
