### ISSUE TITLE
Error: Please add @midwayjs/mock to your devDependencies

### ISSUE THREAD

**Issue by XiaoKun89** [midwayjs/hooks#216]
Node版本：v16.13.0
模板：一体化 + vue

流程：pnpm install -> pnpm dev

运行结果如下图所示：
![image](https://user-images.githubusercontent.com/43437835/155258663-8e3b4dd5-b7f3-469d-bd78-768c4680a629.png)

如果使用npm或yarn能正常运行，则pnpm不行，是否可以兼容pnpm的吗？

**Comment by Lxxyx** [comment]
[Ref: https://github.com/midwayjs/cli/pull/271](https://github.com/midwayjs/cli/pull/271)
