### ISSUE TITLE
开发环境和生产环境安装依赖问题太多了

### ISSUE THREAD

**Issue by ghn9264** [midwayjs/hooks#226]
以hooks - example / vue为例,在开发环境中可以正常安装所有依赖,但在生产环境中始终会缺少几个包,如:vue-plugin等.
在服务器部署的时候,只能用开发环境构建,因为生产环境缺包无法正常使用.开发环境构建好的包只能通过npm start运行,通过Bootstrap启动时又会提示新的错误.

**Comment by Lxxyx** [comment]
Ref: https://github.com/midwayjs/hooks/pull/212

1. 已经在修复类似的问题了，还没有发版
2. 然后构建期确实是应该安装全量依赖的，build tools 都在 devDeps 里
3. Bootstrap启动时又会提示新的错误，有具体的错误和截图吗？

**Comment by Lxxyx** [comment]
相关讨论：https://github.com/midwayjs/hooks/discussions/211

**Comment by ghn9264** [comment]
👌
