### ISSUE TITLE
hooks start 只能访问跟路径(hppt://127.0.0.1:3000)不能直接访问具体的路径(hppt://127.0.0.1:3000/b)。  

### ISSUE THREAD

**Issue by daixiongsheng** [midwayjs/hooks#238]
hooks start 当前端是一个SPA应用时，会出现不能路由。

![image](https://user-images.githubusercontent.com/28498805/156514198-134cb0b1-169a-4422-b068-52912e25c176.png)

这是前端的路由
![image](https://user-images.githubusercontent.com/28498805/156514304-f1da925e-7ac6-4035-ba51-7d59b6150562.png)

curl http://127.0.0.1:3000/a
实际效果
      什么也不返回
期待效果
     返回的 curl http://127.0.0.1:3000 一样的结果

https://github.com/daixiongsheng/issues

**Comment by Lxxyx** [comment]
看起来是期望 SPA 模式下，默认返回 index.html，确保路由能正常使用？

**Comment by daixiongsheng** [comment]
好像没有完全解决
![image](https://user-images.githubusercontent.com/28498805/157793560-af164a13-538a-4a8a-9d2a-ae4930b3e663.png)

一些静态资源请求好像不成功
