### ISSUE TITLE
当有配置globalPrefix时，一体化直接引入node接口会404

### ISSUE THREAD

**Issue by daixiongsheng** [midwayjs/hooks#240]
![image](https://user-images.githubusercontent.com/28498805/156538248-1146c16b-c854-451f-bd87-70d85aa1738c.png)
![image](https://user-images.githubusercontent.com/28498805/156538491-d9024971-2fba-49f1-bd8f-026acc5870c7.png)
![image](https://user-images.githubusercontent.com/28498805/156538002-cb44b39d-2cca-458e-ae19-291630850e0a.png)

**Comment by Lxxyx** [comment]
@daixiongsheng 项目的 `midway.config.[ts|js]` 文件内容发一下

**Comment by Lxxyx** [comment]
目前前后端的编译是分离的，也就意味着前端编译时其实拿不到后端配置的 `globalPrefix`，目前这个问题暂时无解
