### ISSUE TITLE
一体化项目vue案例构建后运行无内容

### ISSUE THREAD

**Issue by mrcdh** [midwayjs/hooks#255]
直接使用官方一体化全栈项目模板(vue)
cnpm run dev没问题正常访问开发
cnpm run build 没报错构件成功，dist相关文件生成
cnpm run start运行后无报错，提示访问地址
![image](https://user-images.githubusercontent.com/38906063/158020805-5f16131a-b1be-4047-a5fc-526e70d906ea.png)

访问localhost:3000状态码204无内容

**Comment by Lxxyx** [comment]
收到，我这边复现一下

**Comment by Lxxyx** [comment]
我这边是正常的，可以提供一下 @midwayjs/hooks 的版本和电脑系统（win/mac）

**Comment by mrcdh** [comment]
我的还是不行，还是那个问题系统：win11专业版21H2 22000.556
node：14.18.3
cnpm: 7.1.0
EDGE: 99.0.1150.39 (正式版本) (64 位)
@midway/hook: 一体化案例 https://github.com/midwayjs/hooks/tree/main/examples/vuecnpm icnpm run dev 正常，可以访问无异常cnpm run build 正常cnpm run start 正常，但是访问204，不能显示




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月14日(星期一) 下午2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [midwayjs/hooks] 一体化项目vue案例构建后运行无内容 (Issue #255)





 
我这边是正常的，可以提供一下 @midwayjs/hooks 的版本和电脑系统（win/mac）
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lxxyx** [comment]
应该是 Windows 的路径判断问题，我找台 windows 看看

**Comment by mrcdh** [comment]
如何了，是我的姿势不对还是win真的有问题
