### ISSUE TITLE
一体化项目参数校验无法捕获错误

### ISSUE THREAD

**Issue by mrcdh** [midwayjs/hooks#268]
![image](https://user-images.githubusercontent.com/38906063/159492753-4549af3b-41de-40b6-8eed-39afb6822152.png)
根据官方案例，无法捕获错误信息进行处理
![image](https://user-images.githubusercontent.com/38906063/159501282-77dbe2fa-654e-4f75-ac21-42ec6226b059.png)

**Comment by mrcdh** [comment]
![image](https://user-images.githubusercontent.com/38906063/159499183-2f98c4d4-cd49-443a-8c28-02a1cfba8211.png)

**Comment by Lxxyx** [comment]
![image](https://user-images.githubusercontent.com/13161470/159636941-28165d2e-052e-402e-ae30-dc98c5272a40.png)
在这个 demo 中我是可以收到具体的错误信息的。然后这个错误会在浏览器的控制台显示，而不是 VSCode

**Comment by mrcdh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            我这结果是页面内容没有，vscode调试控制台没有捕获错误，浏览器控制台确实有捕获错误及响应输出，页面没有显示“这是首页”一片空白

**Comment by Lxxyx** [comment]
> 我这结果是页面内容没有，vscode调试控制台没有捕获错误，浏览器控制台确实有捕获错误及xiang相应输出，页面没有显示“这是首页”一片空白 ![image]([user-images.githubusercontent.com/38906063/159645600-99a64032-a7d5-4625-945f-b667c6ff4944.png](https://user-images.githubusercontent.com/38906063/159645600-99a64032-a7d5-4625-945f-b667c6ff4944.png))

浏览器页面空白吗？

**Comment by mrcdh** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    是的

**Comment by Lxxyx** [comment]
> 是的

删除掉前端调用和 try/catch 部分内容后看看是不是正常，还有就是能不能提供一个简单复现的 demo 我这边排查一下
