### ISSUE TITLE
v3 一体化方案下 socketio 组件不可用

### ISSUE THREAD

**Issue by 94cstyles** [midwayjs/hooks#298]
[demo](https://github.com/94cstyles/midway-hook-demo/tree/scoket)

版本: 3.0.0

尝试使用 socketio 组件，同样的代码在传统方案下 ws 可连接，一体化方案则无响应，唯一的差异就是在引入组件的方式

```ts
import { createConfiguration, hooks } from '@midwayjs/hooks';
import * as Koa from '@midwayjs/koa';
import * as socketio from '@midwayjs/socketio';

export default createConfiguration({
  imports: [Koa, socketio, hooks()],
  ...
})
```

```ts
import { Configuration, App } from '@midwayjs/decorator';
import * as koa from '@midwayjs/koa';
import * as socketio from '@midwayjs/socketio';

@Configuration({
  imports: [
    koa,
    socketio,
   ...
})
```

**Comment by 94cstyles** [comment]
![image](https://user-images.githubusercontent.com/3605154/162130795-8d3c01e0-057f-4cfd-ad8a-e9f3eb0476f3.png)
在组件文档中，描述“端口服务端和客户端一致​”

但保持一致却会抛出异常

![image](https://user-images.githubusercontent.com/3605154/162130917-ecac1cf4-8fbe-4ccd-92ae-6ebabfc6067c.png)

所以应该是一致，还是为空？

**Comment by czy88840616** [comment]
不写。

**Comment by biuuu** [comment]
端口其实默认就是7001，不写或者只写其中一个。
然后客户端使用时需要指定 7001 端口或你自定义的端口才能访问。
```
const socket = io('http://localhost:7001')
```
像上面这样子。
本来我也以为 socketio 跟开发时默认用的 3000 端口一致。
实际使用后发现 koa 也是用的 7001 端口，但 midway 内部做了代理，所以可以直接用 3000 端口访问到 api 接口。
而 socketio 虽然也使用了 7001 端口但并没有被代理到 3000 端口，需要客户端指定 7001 端口访问。

**Comment by biuuu** [comment]
@Lxxyx socketio 不能使用 dev 的 3000 端口访问是 BUG 吗？

**Comment by Lxxyx** [comment]
> @Lxxyx socketio 不能使用 dev 的 3000 端口访问是 BUG 吗？

是的，这部分我在计划重写 dev pack 的逻辑，以支持更多的 Case。当前的话还是需要判断一下，本地走 7001

**Comment by 94cstyles** [comment]
原来如此，谢谢 ~
