### ISSUE TITLE
Midway 一体化项目 无法使用vite --mode 进行自定义环境

### ISSUE THREAD

**Issue by angusun** [midwayjs/hooks#321]
* **Node Version**: 17.3.1
* **Midway Version(Decorator/Core)**: 4.0.15
* **Component Name/Version**: midway
* **Platform**: macOS 11.6
* **Mini Showcase Repository**: git@github.com:angusun/midway-demo.git

使用上述代码仓库，运行npm run build 即可复现。

**Comment by Lxxyx** [comment]
还不支持该选项，因为插件是根据 mode 来设置的，如果有使用到 mode 的场景，建议通过别的方式替换，比如 process.env.NODE_ENV
