### ISSUE TITLE
ERROR: pnpm: [ Midway ] TypeError: The "id" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by birdmanmandbir** [midwayjs/hooks#322]
node版本: v17和v14都试过
模板: react, 一体化
运行结果如下图所示：
![image](https://user-images.githubusercontent.com/48193000/165505850-8c4166ff-6fa6-44b8-a70a-934f6adac15b.png)
npm和yarn都可以, 但pnpm不行, 是否可以兼容pnpm?

**Comment by Lxxyx** [comment]
按理说 pnpm 应该是已经支持的，试试看清除 lock 重装后看看？

**Comment by birdmanmandbir** [comment]
> 按理说 pnpm 应该是已经支持的，试试看清除 lock 重装后看看？

`npx degit https://github.com/midwayjs/hooks/examples/react ./hooks-app` 新建项目, 
pnpm i && pnpm run dev就会报错, please add @midwayjs/mock to your devdependencies

**Comment by Lxxyx** [comment]
@echosoar
