### ISSUE TITLE
一体化场景下使用中间件封装返回结果，前端调用API函数返回类型没有发生相应改变？

### ISSUE THREAD

**Issue by RobertChaw** [midwayjs/hooks#357]
项目中全局使用 responseWrapper 中间件封装一层带执行结果的对象返回给前端。
![image](https://user-images.githubusercontent.com/29568488/172370962-b09dd04a-07ba-412f-b11b-a897305a6d27.png)

但在一体化中，前端调用 API 函数返回类型没有发生相应改变，导致前端获取返回结果时的类型是错误的。
![image](https://user-images.githubusercontent.com/29568488/172371258-fdd7c847-db0b-4d59-ad2c-f04e9f1ae154.png)

除了每次调用时 as 关键词让其正常工作以外，有没有一种更优雅的方式让其正常工作？

**Comment by Lxxyx** [comment]
前端可以使用中间件拆包。参考：https://midwayjs.org/docs/hooks/client#middleware-middleware

```ts
import { setupHttpClient } from '@midwayjs/rpc';
import type { Middleware } from '@midwayjs/rpc';

const unwrap: Middleware = async (
  ctx,
  next
) => {
  await next();
  ctx.res = ctx.res.data
};

setupHttpClient({
  middleware: [unwrap],
});
```
