### ISSUE TITLE
[Bug]: 在一体化 api 接口中，引入 nanoid 在 dev 环境报错

### ISSUE THREAD

**Issue by sinoon** [midwayjs/hooks#364]
复现方式：任意  ./api 目录下接口，引入 nanoid

<img width="1828" alt="image" src="https://user-images.githubusercontent.com/6065488/173241459-1d480f54-a6e7-4e2a-9a44-8e6a76babb83.png">

**Comment by Lxxyx** [comment]
nanoid 只有 esm 的格式，你可以通过 `await import('nanoid')` 来加载，或者使用 v3 版本，这个版本有 cjs 的导出

**Comment by sinoon** [comment]
dynamic import 的方式也是报错的
