### ISSUE TITLE
使用pnpm安装依赖会报错未找到dependency: @midwayjs/hooks-core/request

### ISSUE THREAD

**Issue by Fgoo9527** [midwayjs/hooks#373]
如题所示，使用pnpm安装依赖后无法正常启动项目，是前后端一体化的模板那个

**Comment by Lxxyx** [comment]
> pnpm的问题还是蛮多的，快一年啦

这个我们在试着支持哈，因为我们日常一般也都是 yarn 或者 cnpm/npm，pnpm 用的不多，有些时候单测过了但是实际使用时又会出问题。

这个我再看看，新版本的 https://github.com/midwayjs/hooks/pull/337 应该能解决这个问题

**Comment by sky124380729** [comment]
> 

现在迫切需要解决的是#374这个问题呢，我试了多个node环境，始终报错

**Comment by AshenBird** [comment]
> > pnpm的问题还是蛮多的，快一年啦
> 
> 这个我们在试着支持哈，因为我们日常一般也都是 yarn 或者 cnpm/npm，pnpm 用的不多，有些时候单测过了但是实际使用时又会出问题。
> 
> 这个我再看看，新版本的 #337 应该能解决这个问题

官方通过 Corepack 来引入 pnpm ，很难说日常用的不多。可以认为 node 方面将其视作 npm  的有力竞争者。很多头部项目也开始使用 pnpm 了。

**Comment by zhangfisher** [comment]
使用pnpm有依赖莫名其妙问题,用yarn

**Comment by Lxxyx** [comment]
Midway Hooks 正在转向使用 Pnpm，仍然需要一点时间去排查所有的 pnpm 依赖问题
