### ISSUE TITLE
调试模式下 useContext<Context>（） 获取值为undefined 

### ISSUE THREAD

**Issue by itisl2220** [midwayjs/hooks#374]
调试模式下 useContext<Context>（） 获取值为undefined

**Comment by itisl2220** [comment]
https://user-images.githubusercontent.com/32608524/174499929-5e477648-fc35-485d-810a-e5de7cf3da26.png

**Comment by itisl2220** [comment]
![image](https://user-images.githubusercontent.com/32608524/176997134-599f6ac2-a109-46f1-a271-20e8ff6cfa5f.png)

**Comment by itisl2220** [comment]
https://github.com/midwayjs/hooks/tree/main/examples/vue-faas

**Comment by sky124380729** [comment]
一样的问题

**Comment by Lxxyx** [comment]
Node.js v18 中 v8 的 BUG，升级至 v18.9.0 即可解决。

https://github.com/nodejs/node/issues/43148
