### ISSUE TITLE
Cannot find module 'ts-node/register'

### ISSUE THREAD

**Issue by RenHung** [midwayjs/hooks#391]
npm cnpm yarn 装了好几次，换了yarn源，终于安装完了，yarn dev就爆这错误。Cannot find module 'ts-node/register'

**Comment by RenHung** [comment]
> 

好了，自己手动安装ts-node就行了。

**Comment by zhangbowy** [comment]
![image](https://user-images.githubusercontent.com/33514252/190086966-36e4bc5f-39e6-4a80-b8f0-4c3c6bd648dd.png) 
俺也遇到了, 这个还没改吗

**Comment by birdmanmandbir** [comment]
已提交 #423
