### ISSUE TITLE
一体化项目打包后执行npm run start 资源文件会经过api的中间件，导致返回了接口的信息，run dev是正常的

### ISSUE THREAD

**Issue by baoqing1124** [midwayjs/hooks#399]
打包后的dist路径如下：
<img width="280" alt="image" src="https://user-images.githubusercontent.com/15626996/185374512-8d0fc255-4b4c-47bf-a92d-566bdec8384f.png">
api可以请求，访问页面路径会被当做接口处理，不清楚应该怎么访问才能打开页面
<img width="474" alt="image" src="https://user-images.githubusercontent.com/15626996/185374759-f528ee68-40b5-4748-9139-c075d92927e6.png">
哪位大佬可以帮忙看下是哪里的问题，第一次使用midway没啥经验~

**Comment by Lxxyx** [comment]
本地开发时，前端资源走的是 Vite 的 DevServer，而部署上线后，实际上托管资源的是后端。需要手动在中间件里 exclude 掉前端资源

**Comment by baoqing1124** [comment]
@Lxxyx 原来如此 明白了 感谢大佬~
