### ISSUE TITLE
Cannot read properties of undefined (reading 'getApplication')

### ISSUE THREAD

**Issue by quanzaiyu** [midwayjs/hooks#400]
使用一体化应用Vue3示例，使用yarn安装依赖，运行，报错：

```
[ Midway ] start error: Cannot read properties of undefined (reading 'getApplication')
```

报错截图：
![image](https://user-images.githubusercontent.com/13745132/187327250-4917a0d4-b751-4d65-b46c-f6d170191cc0.png)

尝试使用pnpm，也是报同样的错，npm则依赖安装不上。

**Comment by Lxxyx** [comment]
在本地无法复现此类问题，需要提供复现的例子
