### ISSUE TITLE
零Api调用post接口，该如何设置headers?

### ISSUE THREAD

**Issue by baoqing1124** [midwayjs/hooks#401]
文档中get请求可以通过设置headers参数来实现，但是在post中headers被当做请求参数了
//get请求正常 可以设置headers
const response = await getAuth({
 query:{a:1,b:2},
  headers: { token: '123456' },
});
//post请求设置的headers在请求参数中 不在request headers中
<img width="353" alt="image" src="https://user-images.githubusercontent.com/15626996/187615147-9fb03f1d-808d-4139-8164-a17246066ac5.png">

**Comment by Lxxyx** [comment]
在函数中有使用 `Headers()` 吗？
