### ISSUE TITLE
前端调用Hooks方案的接口如何拦截错误？

### ISSUE THREAD

**Issue by xmsz** [midwayjs/hooks#42]
背景
- 前端调用A接口
- A接口返回状态400
- 前端还是调用成功，而不是捕获到400

需求
- 前端调用A接口的时候，根据ctx来拦截错误
- 前端调用A接口的时候，A接口可以返回Promise.reject，且前端可以拦截到错误

------- 第二个问题 -----

在后端 接口A调用接口B 也如何拦截错误？
现在和前端一样表现都会走成功

**Comment by Lxxyx** [comment]
> 背景
> 
> * 前端调用A接口
> * A接口返回状态400
> * 前端还是调用成功，而不是捕获到400
> 
> 需求
> 
> * 前端调用A接口的时候，根据ctx来拦截错误
> * 前端调用A接口的时候，A接口可以返回Promise.reject，且前端可以拦截到错误
> 
> ------- 第二个问题 -----
> 
> 在后端 接口A调用接口B 也如何拦截错误？
> 现在和前端一样表现都会走成功

前端显示调用成功是因为在 fetch 中没有检验 status，属于 BUG，我会在近期着手对 hooks-request 进行优化。
目前可以先用 axios 覆盖 HTTP 默认请求客户端，确保可以正常报错

**Comment by waitingsong** [comment]
哈哈，看错了项目了，以为是 midway 主项目

**Comment by Lxxyx** [comment]
#48 2.0 版本已使用 axios 替代默认请求客户端
