### ISSUE TITLE
[@vitejs/plugin-react] You should stop using "vite:react-jsx" since this plugin conflicts with it

### ISSUE THREAD

**Issue by zhangfisher** [midwayjs/hooks#432]
1. 使用`https://github.com/midwayjs/hooks/blob/main/examples/react`

2. 将依赖升级到最新的
  "dependencies": {
    "@midwayjs/hooks": "^3.0.0",
    "@midwayjs/hooks-kit": "^3.0.0",
    "@midwayjs/koa": "^3.1.0",
    "@midwayjs/rpc": "^3.0.0",
    "@prisma/client": "4.5.0",
    "ahooks": "^3.1.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-markdown": "8.0.3",
    "react-router-dom": "^6.4.2",
    "zod": "^3.11.6"
  },
  "devDependencies": {
    "@swc/core": "^1.3.11",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@vitejs/plugin-react": "^2.2.0",
    "esno": "^0.16.3",
    "prisma": "^4.5.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.3.5",
    "vite": "3.0.0"
  },
3. 启动后提示错误代码
`[@vitejs/plugin-react] You should stop using "vite:react-jsx" since this plugin conflicts with it`

**Comment by 986244073** [comment]
yarn run v1.22.19
$ hooks dev
[@vitejs/plugin-react] You should stop using "vite:react-jsx" since this plugin conflicts with it.
  > Network:  http://192.168.2.5:3000/
  > Local:    http://localhost:3000/

**Comment by Lxxyx** [comment]
需要在 `@vitejs/plugin-react` 中设置

```
react({
  jsxRuntime: 'classic',
})
```
