### ISSUE TITLE
We will end support for Node.js v12 | 我们将结束对 Node.js v12 版本的支持

### ISSUE THREAD

**Issue by Lxxyx** [midwayjs/hooks#446]
The Node.js community has ended support for Node.js v12, and in the next release of @midwayjs/hooks v3.1, we will also end support.

// CN

Node.js 社区已经结束对 Node.js v12 版本的支持，在接下来的 @midwayjs/hooks v3.1 版本中，我们也将结束支持。

**Comment by Lxxyx** [comment]
Ref: https://github.com/midwayjs/hooks/pull/337/commits/784897a099575d72c6b15577784b66e7d3fee440

**Comment by czy88840616** [comment]
完全不行了吗

**Comment by czy88840616** [comment]
👌
