### ISSUE TITLE
tsconfig里配置里支持commonJs，但编译时依然报错

### ISSUE THREAD

**Issue by wangshaoyuan** [midwayjs/hooks#46]
代码地址
![image](https://user-images.githubusercontent.com/3908565/106855725-6194db00-66f8-11eb-8311-4b14e238b6ec.png)
tsconfig配置如下：
![image](https://user-images.githubusercontent.com/3908565/106855762-71142400-66f8-11eb-9bd7-bd925420fc6b.png)

**Comment by Lxxyx** [comment]
项目中有使用类似 export * from 'mod' 的语法吗？有的话只能暂时先替换这种用法，TS Compiler 的问题，还在等他们 fix

**Comment by wangshaoyuan** [comment]
> 项目中有使用类似 export * from 'mod' 的语法吗？有的话只能暂时先替换这种用法，TS Compiler 的问题，还在等他们 fix

有的，在引用第三方模块的时候，第三方模块有这种语法，需要等哪位同学修复哈？

**Comment by wangshaoyuan** [comment]
> 项目中有使用类似 export * from 'mod' 的语法吗？有的话只能暂时先替换这种用法，TS Compiler 的问题，还在等他们 fix

大概多久能修复～，除了替换写法以外，是否还有别的方案？

**Comment by Lxxyx** [comment]
> > 项目中有使用类似 export * from 'mod' 的语法吗？有的话只能暂时先替换这种用法，TS Compiler 的问题，还在等他们 fix
> 
> 有的，在引用第三方模块的时候，第三方模块有这种语法，需要等哪位同学修复哈？

应该只影响源码的，稍等我看看

**Comment by Lxxyx** [comment]
> 大概多久能修复～，除了替换写法以外，是否还有别的方案？
有新方案，我们提供了新的 runtime，可以试用 #40
