### ISSUE TITLE
发现个小问题，不确定是 bug ，还是我的用法有误

### ISSUE THREAD

**Issue by 15835196981** [midwayjs/hooks#486]
接口有 2 个文件，分别是 user.ts 和 role.ts，它们各自都导出个叫 list 的接口，

dev 时，只有 user/list 接口可调通，role/list 接口为 404

build后，2 个接口都可以调通

---

所以不太确定是：
1. 用法有误，即使 2 个文件下，也不应该有同名函数
2. dev 时生成的 router 有点bug...

---

大佬们看一下吧~~~

这个是demo：https://github.com/15835196981/midway-test

**Comment by Lxxyx** [comment]
我看一下

**Comment by Lxxyx** [comment]
> @Lxxyx 大佬看过了吗 咋样呀

<img width="675" alt="image" src="https://user-images.githubusercontent.com/13161470/207792576-b5ce0a99-6882-494d-8f98-142e231f2cbb.png">

我在我本地试过了，并没有复现此情况
