### ISSUE TITLE
如何定义自定义的接口？

### ISSUE THREAD

**Issue by Lizhooh** [midwayjs/hooks#85]
有部分接口通过 hooks 的能力生成接口代码，

有部分想自定义编写接口代码，应该如何编写？

**Comment by Lxxyx** [comment]
你好，感谢反馈。

自定义编写接口指的是后端开发，还是前端如何请求？ @Lizhooh

**Comment by Lizhooh** [comment]
@Lxxyx 在 Nodejs 端怎么自定义接口？

**Comment by Lxxyx** [comment]
> @Lxxyx 在 Nodejs 端怎么自定义接口？

在 lambda 文件夹下，导出一个异步函数即可，那个就是接口

**Comment by Lizhooh** [comment]
@Lxxyx 非样板生成的接口，能定义不，不是自动生成那种？

**Comment by Lxxyx** [comment]
> @Lxxyx 非样板生成的接口，能定义不，不是自动生成那种？

这个目前还不支持
