### ISSUE TITLE
examples 下边 vue的demo 

### ISSUE THREAD

**Issue by xiaobo1215** [midwayjs/hooks#88]
没有实现服务端渲染？  从目前的demo来看，数据是在客户端获取然后渲染dom

**Comment by Lxxyx** [comment]
> 没有实现服务端渲染？ 从目前的demo来看，数据是在客户端获取然后渲染dom

对的，目前走的还是客户端渲染的模式。Vite 在 SSR 的支持应该会由 nuxt.js 做掉，到时候支持 nuxt.js 即可
